#!/usr/bin/env bash

## Set GTK Themes, Icons, Cursor and Fonts

THEME='Gruvbox'
ICONS='Luv-Folders-Dark'
FONT='Jetbrains Mono Nerd Font 11'
CURSOR='Sweet'

SCHEMA='gsettings set org.gnome.desktop.interface'

apply_themes () {
	${SCHEMA} gtk-theme "$THEME"
	${SCHEMA} icon-theme "$ICONS"
	${SCHEMA} cursor-theme "$CURSOR"
	${SCHEMA} font-name "$FONT"
}

apply_themes
